AWSTemplateFormatVersion: 2010-09-09
Description: 'Automated deployment of QuickSight Assets.'

Parameters:
  1stReadMe:
    Type: String
    Default: README
    Description: 'PREREQUISITES - 1) QuickSight should be setup on the aws account, 2) An user with author/admin role should be setup in QuickSight. 3)SPICE capacity should be available in the region where you are creating this stack.'

  QuickSightIdentityRegion:
    Type: String
    MinLength: 1
    Description: REQUIRED - QuickSight identity region (region where your users are managed; run list-users command and check the user arn if you are not sure of the identity region).

  QuickSightUser:
    Type: String
    MinLength: 1
    Description: REQUIRED - User name of QuickSight author/admin from default namespace (as displayed in QuickSight admin panel). Dashboard created by this template with be shared with this user.

  Suffix:
    Type: String
    Description: OPTIONAL - If you need to create multiple instances of this sample on same aws account, add a short NUMERIC suffix here.
Resources:
  QSTCFBuildQSDataSource:
    Type: AWS::QuickSight::DataSource
    Properties:
      DataSourceId: !Join
        - ''
        - - QSTCF-DataSource
          - !Ref Suffix
      Name: !Join
        - ''
        - - QSTCF-DataSource
          - !Ref Suffix
      AwsAccountId: !Ref AWS::AccountId
      Type: S3
      DataSourceParameters:
        S3Parameters:
          ManifestFileLocation:
            Bucket: ee-assets-prod-us-east-1
            Key: modules/337d5d05acc64a6fa37bcba6b921071c/v1/SalesDataManifest.json
      Permissions:
        - Principal: !Join
            - ''
            - - 'arn:aws:quicksight:'
              - !Ref QuickSightIdentityRegion
              - ':'
              - !Ref AWS::AccountId
              - ':user/default/'
              - !Ref QuickSightUser
          Actions:
            - quicksight:UpdateDataSourcePermissions
            - quicksight:DescribeDataSource
            - quicksight:DescribeDataSourcePermissions
            - quicksight:PassDataSource
            - quicksight:UpdateDataSource
            - quicksight:DeleteDataSource

  QSTCFBuildQSDataSet:
    Type: AWS::QuickSight::DataSet
    Properties:
      DataSetId: !Join
        - ''
        - - QSTCF-DataSet
          - !Ref Suffix
      Name: !Join
        - ''
        - - QSTCF-DataSet
          - !Ref Suffix
      AwsAccountId: !Ref AWS::AccountId
      PhysicalTableMap:
          PhysicalTable1:
            S3Source:
              DataSourceArn: !GetAtt QSTCFBuildQSDataSource.Arn
              InputColumns:
              - Name: ColumnId-1
                Type: STRING
              - Name: ColumnId-2
                Type: STRING
              - Name: ColumnId-3
                Type: STRING
              - Name: ColumnId-4
                Type: STRING
              - Name: ColumnId-5
                Type: STRING
              - Name: ColumnId-6
                Type: STRING
              - Name: ColumnId-7
                Type: STRING
              - Name: ColumnId-8
                Type: STRING
              - Name: ColumnId-9
                Type: STRING
              - Name: ColumnId-10
                Type: STRING
              - Name: ColumnId-11
                Type: STRING
              - Name: ColumnId-12
                Type: STRING
              UploadSettings:
                ContainsHeader: true
                Delimiter: ','
                Format: CSV
                StartFromRow: 1
                TextQualifier: DOUBLE_QUOTE
      LogicalTableMap:
          LogicalTable1:
            Alias: QSTCF-DataSet
            DataTransforms:
            - RenameColumnOperation:
                ColumnName: ColumnId-1
                NewColumnName: Date
            - CastColumnTypeOperation:
                ColumnName: Date
                Format: M/d/yyyy
                NewColumnType: DATETIME
            - RenameColumnOperation:
                ColumnName: ColumnId-2
                NewColumnName: Salesperson
            - RenameColumnOperation:
                ColumnName: ColumnId-3
                NewColumnName: Lead Name
            - RenameColumnOperation:
                ColumnName: ColumnId-4
                NewColumnName: Segment
            - RenameColumnOperation:
                ColumnName: ColumnId-5
                NewColumnName: Region
            - RenameColumnOperation:
                ColumnName: ColumnId-6
                NewColumnName: Target Close
            - CastColumnTypeOperation:
                ColumnName: Target Close
                Format: M/d/yyyy
                NewColumnType: DATETIME
            - RenameColumnOperation:
                ColumnName: ColumnId-7
                NewColumnName: Forecasted Monthly Revenue
            - CastColumnTypeOperation:
                ColumnName: Forecasted Monthly Revenue
                NewColumnType: INTEGER
            - RenameColumnOperation:
                ColumnName: ColumnId-8
                NewColumnName: Opportunity Stage
            - RenameColumnOperation:
                ColumnName: ColumnId-9
                NewColumnName: Weighted Revenue
            - CastColumnTypeOperation:
                ColumnName: Weighted Revenue
                NewColumnType: INTEGER
            - RenameColumnOperation:
                ColumnName: ColumnId-10
                NewColumnName: Is Closed
            - RenameColumnOperation:
                ColumnName: ColumnId-11
                NewColumnName: ActiveItem
            - RenameColumnOperation:
                ColumnName: ColumnId-12
                NewColumnName: IsLatest
            - CastColumnTypeOperation:
                ColumnName: IsLatest
                NewColumnType: INTEGER
            - TagColumnOperation:
                ColumnName: Region
                Tags:
                - ColumnGeographicRole: STATE
            - ProjectOperation:
                ProjectedColumns:
                - Date
                - Salesperson
                - Lead Name
                - Segment
                - Region
                - Target Close
                - Forecasted Monthly Revenue
                - Opportunity Stage
                - Weighted Revenue
                - Is Closed
                - ActiveItem
                - IsLatest
            Source:
              PhysicalTableId: PhysicalTable1
      Permissions:
          - Principal: !Join
              - ''
              - - 'arn:aws:quicksight:'
                - !Ref QuickSightIdentityRegion
                - ':'
                - !Ref AWS::AccountId
                - ':user/default/'
                - !Ref QuickSightUser
            Actions:
              - quicksight:UpdateDataSetPermissions
              - quicksight:DescribeDataSet
              - quicksight:DescribeDataSetPermissions
              - quicksight:PassDataSet
              - quicksight:DescribeIngestion
              - quicksight:ListIngestions
              - quicksight:UpdateDataSet
              - quicksight:DeleteDataSet
              - quicksight:CreateIngestion
              - quicksight:CancelIngestion
      ImportMode: SPICE
      RowLevelPermissionTagConfiguration:
        Status: ENABLED
        TagRules:
          - TagKey: region_tag
            ColumnName: Region
          - TagKey: segment_tag
            ColumnName: Segment
        TagRuleConfigurations:
          - [ region_tag , segment_tag ]

  QSTCFBuildQSTheme:
    Type: AWS::QuickSight::Theme
    Properties:
      ThemeId: !Join
        - ''
        - - QSTCF-Theme
          - !Ref Suffix
      Name: !Join
        - ''
        - - QSTCF-Theme
          - !Ref Suffix
      AwsAccountId: !Ref AWS::AccountId
      BaseThemeId: SEASIDE
      Configuration:
        UIColorPalette:
          PrimaryBackground: '#EEEEEE'
          SecondaryBackground: '#EEEEEE'
      Permissions:
        - Principal: !Join
            - ''
            - - 'arn:aws:quicksight:'
              - !Ref QuickSightIdentityRegion
              - ':'
              - !Ref AWS::AccountId
              - ':user/default/'
              - !Ref QuickSightUser
          Actions:
            - quicksight:UpdateThemeAlias
            - quicksight:ListThemeVersions
            - quicksight:UpdateThemePermissions
            - quicksight:DescribeThemeAlias
            - quicksight:DeleteThemeAlias
            - quicksight:DeleteTheme
            - quicksight:ListThemeAliases
            - quicksight:DescribeTheme
            - quicksight:CreateThemeAlias
            - quicksight:UpdateTheme
            - quicksight:DescribeThemePermissions
      VersionDescription: Initial version

  QSTCFBuildQSTemplate:
    Type: AWS::QuickSight::Template
    Properties:
      TemplateId: !Join
        - ''
        - - QSTCF-Template
          - !Ref Suffix
      Name: !Join
        - ''
        - - QSTCF-Template
          - !Ref Suffix
      AwsAccountId: !Ref AWS::AccountId
      SourceEntity:
        SourceTemplate:
          Arn: arn:aws:quicksight:us-east-1:874374045911:template/QSTCF-Template
      Permissions:
        - Principal: !Join
            - ''
            - - 'arn:aws:quicksight:'
              - !Ref QuickSightIdentityRegion
              - ':'
              - !Ref AWS::AccountId
              - ':user/default/'
              - !Ref QuickSightUser
          Actions:
            - quicksight:DescribeTemplate
      VersionDescription: Initial version - Copied over from AWS account.

  QSTCFBuildQSAnalysis:
    Type: AWS::QuickSight::Analysis
    Properties:
      AnalysisId: !Join
        - ''
        - - QSTCF-Analysis
          - !Ref Suffix
      Name: !Join
        - ''
        - - QSTCF-Analysis
          - !Ref Suffix
      AwsAccountId: !Ref AWS::AccountId
      SourceEntity:
        SourceTemplate:
          Arn: !GetAtt QSTCFBuildQSTemplate.Arn
          DataSetReferences:
            - DataSetPlaceholder: SalesData
              DataSetArn: !GetAtt QSTCFBuildQSDataSet.Arn
      Permissions:
        - Principal: !Join
            - ''
            - - 'arn:aws:quicksight:'
              - !Ref QuickSightIdentityRegion
              - ':'
              - !Ref AWS::AccountId
              - ':user/default/'
              - !Ref QuickSightUser
          Actions:
            - quicksight:RestoreAnalysis
            - quicksight:UpdateAnalysisPermissions
            - quicksight:DeleteAnalysis
            - quicksight:DescribeAnalysisPermissions
            - quicksight:QueryAnalysis
            - quicksight:DescribeAnalysis
            - quicksight:UpdateAnalysis
      ThemeArn: !GetAtt QSTCFBuildQSTheme.Arn

  QSTCFBuildQSDashboard:
    Type: AWS::QuickSight::Dashboard
    Properties:
      DashboardId: !Join
        - ''
        - - QSTCF-Dashboard
          - !Ref Suffix
      Name: !Join
        - ''
        - - QSTCF-Dashboard
          - !Ref Suffix
      AwsAccountId: !Ref AWS::AccountId
      SourceEntity:
        SourceTemplate:
          Arn: !GetAtt QSTCFBuildQSTemplate.Arn
          DataSetReferences:
            - DataSetPlaceholder: SalesData
              DataSetArn: !GetAtt QSTCFBuildQSDataSet.Arn
      Permissions:
        - Principal: !Join
            - ''
            - - 'arn:aws:quicksight:'
              - !Ref QuickSightIdentityRegion
              - ':'
              - !Ref AWS::AccountId
              - ':user/default/'
              - !Ref QuickSightUser
          Actions:
            - quicksight:DescribeDashboard
            - quicksight:ListDashboardVersions
            - quicksight:UpdateDashboardPermissions
            - quicksight:QueryDashboard
            - quicksight:UpdateDashboard
            - quicksight:DeleteDashboard
            - quicksight:DescribeDashboardPermissions
            - quicksight:UpdateDashboardPublishedVersion
      ThemeArn: !GetAtt QSTCFBuildQSTheme.Arn
      DashboardPublishOptions:
        AdHocFilteringOption:
          AvailabilityStatus: DISABLED
